plugins:
  multilingual_enabled:
    default: true
    client: true
  multilingual_content_languages_enabled:
    default: false
    client: true
    validator: ContentLanguagesValidator
  multilingual_content_languages_topic_filtering_enabled:
    default: true
    client: true
  multilingual_guest_language_switcher:
    client: true
    type: enum
    default: "off"
    choices:
      - "off"
      - "footer"
      - "header"
    validator: LanguageSwitcherValidator
  multilingual_guest_language_switcher_footer_visible:
    type: list
    default: ar|zh_CN|en|es|fr|ru
    client: true
  multilingual_require_content_language_tag:
    type: enum
    default: "non-staff"
    choices:
      - "no"
      - "yes"
      - "non-staff"
  multilingual_tag_translations_enforce_format: false
  multilingual_translator_content_tag_sync:
    default: false
    validator: TranslatorContentTagValidator
